#!/usr/bin/env python3
"""
recon_phase1_one_stage.py (v1.5 - Integrated with Passive Artifacts)
-----------------------------------------
One-stage Phase-1 runner + rich debug logging.
UPDATED: Automatically bridges new passive addon outputs (secrets, tech, cloud)
into 'analysis/domain_artifacts.jsonl' for ReconAggregator ingestion.
"""
from __future__ import annotations
import argparse, os, sys, subprocess, json, traceback, time, csv, shlex
from pathlib import Path
from typing import List, Dict, Any, Optional
from phase1_addons import run_phase1_addons

START_TS = time.time()
GLOBAL_LOG: Path | None = None

def ts() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

def log(msg: str, logfile: Path | None = None):
    line = f"[{ts()}] {msg}"
    print(line, file=sys.stderr)
    try:
        if logfile:
            logfile.parent.mkdir(parents=True, exist_ok=True)
            with logfile.open("a", encoding="utf-8") as f:
                f.write(line + "\n")
        if GLOBAL_LOG:
            GLOBAL_LOG.parent.mkdir(parents=True, exist_ok=True)
            with GLOBAL_LOG.open("a", encoding="utf-8") as f:
                f.write(line + "\n")
    except Exception:
        pass

def read_lines(p: Path) -> list[str]:
    if not p.exists(): return []
    return [ln.strip() for ln in p.read_text(encoding="utf-8", errors="ignore").splitlines() if ln.strip()]

def write_text(p: Path, s: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")

def load_domains(fp: str) -> List[str]:
    out = []
    with open(fp, "r", encoding="utf-8", errors="ignore") as f:
        for ln in f:
            ln = ln.strip()
            if not ln or ln.startswith("#"):
                continue
            out.append(ln.strip().strip("."))
    # de-dup keep order
    seen = set(); res = []
    for d in out:
        if d.lower() not in seen:
            seen.add(d.lower()); res.append(d)
    return res

def merge_union_with_addons(domain_dir: Path, dlog: Path | None = None) -> Path:
    core = domain_dir / "all_urls.txt"
    addons = domain_dir / "multiaddons_union.txt"
    out = domain_dir / "all_urls_plus_addons.txt"
    core_lines = set(read_lines(core))
    addons_lines = set(read_lines(addons))
    merged = sorted(core_lines | addons_lines)
    write_text(out, "\n".join(merged) + ("\n" if merged else ""))
    log(f"merge: core={len(core_lines)} addons={len(addons_lines)} merged={len(merged)} -> {out.name}", dlog)
    return out

def file_info(path: Path) -> Dict[str, Any]:
    return {
        "exists": path.exists(),
        "size_bytes": (path.stat().st_size if path.exists() else 0),
        "lines": (len(read_lines(path)) if path.exists() else 0),
        "path": path.as_posix()
    }

# --- NEW: Artifact Bridge Logic ---
def emit_artifact(
    domain_dir: Path,
    domain: str,
    name: str,
    title: str,
    source: str,
    tags: List[str],
    payload: Any
) -> None:
    """Appends a JSON artifact entry to analysis/domain_artifacts.jsonl"""
    analysis_dir = domain_dir / "analysis"
    analysis_dir.mkdir(parents=True, exist_ok=True)
    artifacts_file = analysis_dir / "domain_artifacts.jsonl"
    
    entry = {
        "domain": domain,
        "name": name,
        "title": title,
        "source": source,
        "tags": ",".join(tags) if isinstance(tags, list) else tags,
        "data": payload,
        "timestamp": int(time.time())
    }
    
    try:
        with artifacts_file.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
    except Exception as e:
        pass

def bridge_passive_artifacts(domain_dir: Path, domain: str, out_paths: Dict[str, str], dlog: Path | None):
    """
    Checks for the specific files generated by phase1_addons.py and 
    emits them as generic artifacts for ReconAggregator.
    """
    # 1. Passive Secrets
    if "passive_secrets.json" in out_paths:
        p = Path(out_paths["passive_secrets.json"])
        if p.exists() and p.stat().st_size > 0:
            try:
                data = json.loads(p.read_text(encoding="utf-8"))
                if data:
                    emit_artifact(
                        domain_dir, domain,
                        name="passive.secrets",
                        title=f"Passive Secrets ({len(data)})",
                        source="phase1_addons",
                        tags=["secrets", "passive", "critical"],
                        payload=data
                    )
                    log(f"[{domain}] Bridged {len(data)} passive secrets to artifacts.", dlog)
            except Exception as e:
                log(f"[{domain}] Error bridging secrets: {e}", dlog)

    # 2. Cloud Permutations
    if "cloud_permutations.txt" in out_paths:
        p = Path(out_paths["cloud_permutations.txt"])
        lines = read_lines(p)
        if lines:
            emit_artifact(
                domain_dir, domain,
                name="passive.cloud_perms",
                title=f"Cloud Permutations ({len(lines)})",
                source="phase1_addons",
                tags=["cloud", "passive", "generation"],
                payload={"count": len(lines), "samples": lines[:50], "full_list_file": p.name}
            )
            log(f"[{domain}] Bridged cloud permutations to artifacts.", dlog)

    # 3. Archived Tech
    if "archived_tech.csv" in out_paths:
        p = Path(out_paths["archived_tech.csv"])
        if p.exists():
            tech_entries = []
            try:
                with p.open("r", encoding="utf-8") as f:
                    reader = csv.DictReader(f)
                    for row in reader:
                        tech_entries.append(row)
                if tech_entries:
                    emit_artifact(
                        domain_dir, domain,
                        name="passive.tech",
                        title=f"Archived Tech Stack ({len(tech_entries)})",
                        source="phase1_addons",
                        tags=["tech", "passive", "fingerprint"],
                        payload=tech_entries
                    )
                    log(f"[{domain}] Bridged archived tech to artifacts.", dlog)
            except Exception as e:
                log(f"[{domain}] Error bridging tech: {e}", dlog)

def main(argv=None):
    p = argparse.ArgumentParser(description="One-stage Phase-1 pipeline + addons (Integrated v1.5)")
    p.add_argument("-i","--input", required=True, help="Allowed domains file")
    p.add_argument("-o","--outdir", required=True, help="Output root directory")
    p.add_argument("--verbose", action="store_true")
    p.add_argument("--debug", action="store_true")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--domain-filter", nargs="*", default=[], help="Only process these domains from input")
    # passthrough for recon_pipeline (we forward unknown args)
    default_pipeline = f"python3 {Path(__file__).resolve().with_name('recon_pipeline.py')}"
    p.add_argument("--pipeline-cmd", default=default_pipeline, help="How to invoke recon_pipeline.py")
    # Addons toggles/inputs
    p.add_argument("--enable-phase1-addons", choices=["yes","no"], default="yes")
    p.add_argument("--allowed-domains-file", default="~/.config/recon_automation/allowed_domains.txt")

    # Strict scope policy (preferred): suffix roots + exact hosts + exclusions
    p.add_argument("--strict-scope", choices=["yes","no"], default="yes")
    p.add_argument("--allowed-suffixes-file", default="")
    p.add_argument("--allowed-exact-hosts-file", default="")
    p.add_argument("--exclude-hosts-file", default="")
    p.add_argument("--sonar-fdns", nargs="*", default=[])
    p.add_argument("--sonar-rdns", nargs="*", default=[])
    p.add_argument("--org-keywords", nargs="*", default=[])
    p.add_argument("--container-orgs", nargs="*", default=[])
    p.add_argument("--no-network", choices=["yes","no"], default="no", help="Disable network-dependent addon fetches")
    p.add_argument("--addons-only", choices=["yes","no"], default="no", help="Skip running recon_pipeline; run addons only")
    args, unknown = p.parse_known_args(argv)

    out_root = Path(args.outdir).resolve()
    out_root.mkdir(parents=True, exist_ok=True)
    global GLOBAL_LOG
    GLOBAL_LOG = out_root / "_one_stage_debug.log"

    log(f"one-stage start | outdir={out_root} | input={args.input} | addons_only={args.addons_only} | debug={args.debug}")
    log(f"env: no_network={args.no_network} | addons={args.enable_phase1_addons} | pipeline_cmd={args.pipeline_cmd}")

    # 0) Pre-flight
    allowed_file = Path(os.path.expanduser(args.allowed_domains_file))
    suf_file = Path(os.path.expanduser(args.allowed_suffixes_file)) if args.allowed_suffixes_file else None
    exact_file = Path(os.path.expanduser(args.allowed_exact_hosts_file)) if args.allowed_exact_hosts_file else None
    excl_file = Path(os.path.expanduser(args.exclude_hosts_file)) if args.exclude_hosts_file else None

    if (suf_file and suf_file.exists()) or (exact_file and exact_file.exists()):
        log(f"scope: strict={args.strict_scope} suffixes={suf_file} exact={exact_file} exclude={excl_file}")
    else:
        if not allowed_file.exists():
            log(f"WARNING: allowed_domains_file not found: {allowed_file}")
        log("WARNING: no strict scope files provided; pipeline/addons may fall back to legacy behavior")
    domains = load_domains(args.input)
    if args.domain_filter:
        df = set([d.lower() for d in args.domain_filter])
        domains = [d for d in domains if d.lower() in df]
        log(f"domain_filter active: {len(domains)} domains selected")
    log(f"domains loaded: {len(domains)} -> {domains if args.debug else '[hidden]'}")

    if args.dry_run:
        log("DRY RUN: exiting before executing pipeline/addons")
        return

    # 1) Run recon_pipeline unless addons-only
    if args.addons_only == "no":
        cmd = shlex.split(args.pipeline_cmd) + ["-i", args.input, "-o", args.outdir]
        #if args.verbose or args.debug: cmd.append("--verbose")

        # Forward strict scope policy explicitly (these args are consumed by this wrapper, so they won't be in `unknown`)
        if args.strict_scope:
            cmd += ["--strict-scope", args.strict_scope]
        if args.allowed_suffixes_file:
            cmd += ["--allowed-suffixes-file", args.allowed_suffixes_file]
        if args.allowed_exact_hosts_file:
            cmd += ["--allowed-exact-hosts-file", args.allowed_exact_hosts_file]
        if args.exclude_hosts_file:
            cmd += ["--exclude-hosts-file", args.exclude_hosts_file]

        cmd += unknown  # forward all extra flags to recon_pipeline
        log(f">>> RUN: {' '.join(cmd)}")
        try:
            log(f">>> Executing: {' '.join(cmd)}")
            
            # Use Popen to read line-by-line in real-time
            process = subprocess.Popen(
                cmd, 
                stdout=subprocess.PIPE, 
                stderr=subprocess.STDOUT, 
                text=True,
                bufsize=1 # Line buffered
            )

            # Stream output to terminal AND the log file simultaneously
            if process.stdout:
                for line in process.stdout:
                    # sys.stdout.write reaches your screen
                    sys.stdout.write(line)
                    # log() reaches your _one_stage_debug.log
                    log(f"| {line.strip()}", logfile=None) 

            res_code = process.wait()
            log(f"pipeline exit={res_code}")
            
            if res_code != 0:
                log("ERROR: recon_pipeline.py failed; aborting one-stage wrapper.")
                sys.exit(res_code)

        except FileNotFoundError:
            log("ERROR: pipeline command not found. Check --pipeline-cmd path.")
            sys.exit(127)

    # 2) Run addons per domain
    if args.enable_phase1_addons == "yes":
        for domain in domains:
            ddir = out_root / domain
            dlog = ddir / "logs/phase1_addons_debug.log"
            try:
                log(f"[{domain}] begin addons | dir={ddir}", dlog)
                if not ddir.exists():
                    log(f"[{domain}] WARN: domain dir does not exist (did pipeline create it?): {ddir}", dlog)
                # core files snapshot
                core_info = file_info(ddir / "all_urls.txt")
                log(f"[{domain}] pre-core all_urls.txt -> {core_info}", dlog)

                cc_bodies_dir = (ddir / "cc_bodies")
                out_paths = run_phase1_addons(
                    domain=domain,
                    output_root=ddir,
                    allowed_suffixes_file=(Path(os.path.expanduser(args.allowed_suffixes_file)) if args.allowed_suffixes_file else None),
                    allowed_exact_hosts_file=(Path(os.path.expanduser(args.allowed_exact_hosts_file)) if args.allowed_exact_hosts_file else None),
                    exclude_hosts_file=(Path(os.path.expanduser(args.exclude_hosts_file)) if args.exclude_hosts_file else None),
                    allowed_domains_file=Path(os.path.expanduser(args.allowed_domains_file)) if args.allowed_domains_file else None,
                    sonar_fdns_paths=args.sonar_fdns,
                    sonar_rdns_paths=args.sonar_rdns,
                    cc_bodies_dir=str(cc_bodies_dir) if cc_bodies_dir.exists() else None,
                    org_keywords=args.org_keywords,
                    container_orgs=args.container_orgs,
                    enable_network=(args.no_network == "no"),
                )
                log(f"[{domain}] addons returned {len(out_paths)} paths", dlog)
                
                # --- NEW: Bridge Passive Artifacts to ReconAggregator ---
                bridge_passive_artifacts(ddir, domain, out_paths, dlog)
                # --------------------------------------------------------

                # check each path
                stats = {"domain": domain, "inputs": {
                            "allowed_file": str(args.allowed_domains_file),
                            "sonar_fdns": args.sonar_fdns,
                            "sonar_rdns": args.sonar_rdns,
                            "cc_bodies_dir": (str(cc_bodies_dir) if cc_bodies_dir.exists() else None),
                            "org_keywords": args.org_keywords,
                            "container_orgs": args.container_orgs,
                            "network_enabled": (args.no_network == "no")
                         },
                         "outputs": {}, "merge": {}}
                for k, pth in out_paths.items():
                    ip = Path(pth)
                    info = file_info(ip)
                    stats["outputs"][k] = info
                    flag = "OK" if info["exists"] and info["size_bytes"] > 0 else "EMPTY"
                    log(f"[{domain}] {k}: {flag} | size={info['size_bytes']} | lines={info['lines']} | path={info['path']}", dlog)

                merged = merge_union_with_addons(ddir, dlog)
                m_info = file_info(merged)
                a_info = file_info(ddir / "multiaddons_union.txt")
                c_info = file_info(ddir / "all_urls.txt")
                stats["merge"] = {"core": c_info, "addons": a_info, "merged": m_info}

                # write per-domain summary
                (ddir / "debug_summary.json").write_text(json.dumps(stats, indent=2), encoding="utf-8")
                log(f"[{domain}] summary written: {ddir/'debug_summary.json'}", dlog)
                log(f"[{domain}] done addons", dlog)
            except Exception as e:
                log(f"[{domain}] ERROR: {e}\n{traceback.format_exc()}", dlog)

    dur = time.time() - START_TS
    log(f"one-stage done in {dur:.1f}s")

if __name__ == "__main__":
    main()